var myString;
var myNum;
var myBoo1;
var myVar;
var strArr;
var booArr;
myString = "Hello World" + " My name is Ramona";
myNum = 5 + 5;
myBoo1 = false;
myVar = 5;
strArr = ['hello', 'world', 'my', 'name', 'is', 'Ramona'];
var boo1Arr;
var strNumTuple;
console.log(myBoo1);
console.log(myString);
console.log(myVar);
console.log(strArr);
boo1Arr = [true, false, true];
strNumTuple = ['Hello', 4];
console.log(strNumTuple);
